name: Run Django CLI

on:
  pull_request:
    branches:
      - main  
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install pipx and Poetry
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pipx
        pipx ensurepath
        pipx install poetry

    - name: Install dependencies with Poetry
      working-directory: Backend
      run: |
        poetry install

    - name: Run tests
      working-directory: Backend
      run: |
        poetry run python manage.py test
